/**
 * TS file content generation only. No Node built-ins.
 * Safe to import from browser (authoring app).
 */

/**
 * @param {string} importPath
 * @param {string} importName
 * @param {string} exportName
 * @param {unknown} value
 * @returns {string} Full TS file content
 */
export function generateTsFile(importPath, importName, exportName, value) {
  const objectLiteral = JSON.stringify(value, null, 2)
  return [
    '// Auto-generated by build-data. Do not edit manually.',
    `import type { ${importName} } from '${importPath}'`,
    '',
    `export const ${exportName}: Record<string, ${importName}> = ${objectLiteral}`,
    '',
  ].join('\n')
}
