// Auto-generated by build-data. Do not edit manually.
import type { CombatEncounter } from '../types/combat'

export const COMBAT_ENCOUNTERS: Record<string, CombatEncounter> = {
  "combat_alley_thug": {
    "id": "combat_alley_thug",
    "name": "combat_alley_thug",
    "type": "combat",
    "enemies": [
      {
        "enemyId": "silk_thug",
        "count": 1
      }
    ],
    "resolution": {
      "onVictory": {
        "nextNodeId": "n_alley_thug_looted"
      },
      "onDefeat": {
        "nextNodeId": "n_game_over"
      }
    }
  },
  "combat_boss_garrick": {
    "id": "combat_boss_garrick",
    "name": "combat_boss_garrick",
    "type": "combat",
    "enemies": [
      {
        "enemyId": "silk_enforcer",
        "count": 1
      }
    ],
    "resolution": {
      "onVictory": {
        "nextNodeId": "n_boss_defeated"
      },
      "onDefeat": {
        "nextNodeId": "n_game_over"
      }
    }
  }
}
