// Auto-generated by build-data. Do not edit manually.
import type { EnemyTemplate } from '../types/combat'

export const ENEMY_DICTIONARY: Record<string, EnemyTemplate> = {
  "silk_thug": {
    "id": "silk_thug",
    "name": "Silk Mask Thug",
    "hp": 15,
    "ac": 12,
    "attackBonus": 3,
    "damage": "1d6",
    "xpReward": 35
  },
  "silk_enforcer": {
    "id": "silk_enforcer",
    "name": "Garrick the Enforcer",
    "hp": 25,
    "ac": 14,
    "attackBonus": 4,
    "damage": "1d8",
    "xpReward": 100
  }
}
