// Auto-generated by build-data. Do not edit manually.
import type { EnemyTemplate } from '../types/combat'

export const ENEMY_DICTIONARY: Record<string, EnemyTemplate> = {
  "owlbear": {
    "id": "owlbear",
    "name": "MacGuffin the Owlbear",
    "hp": 59,
    "ac": 13,
    "attackBonus": 7,
    "damage": "1d10+5",
    "xpReward": 200
  },
  "mik_tystone": {
    "id": "mik_tystone",
    "name": "Mik Tystone",
    "hp": 80,
    "ac": 15,
    "attackBonus": 8,
    "damage": "1d6+4",
    "xpReward": 500
  }
}
