// Auto-generated by build-data. Do not edit manually.
import type { ItemTemplate } from '../types/items'

export const ITEM_DICTIONARY: Record<string, ItemTemplate> = {
  "dagger_iron": {
    "id": "dagger_iron",
    "name": "Iron Dagger",
    "type": "weapon",
    "damage": "1d4",
    "attackBonus": 0,
    "acBonus": 0,
    "scalingAttribute": "dexterity",
    "aoe": false
  },
  "blade_of_shadows": {
    "id": "blade_of_shadows",
    "name": "Blade of Shadows",
    "type": "weapon",
    "damage": "1d6",
    "attackBonus": 1,
    "acBonus": 0,
    "scalingAttribute": "dexterity",
    "aoe": false
  },
  "health_potion": {
    "id": "health_potion",
    "name": "Health Potion",
    "type": "consumable",
    "effect": {
      "action": "heal",
      "amount": "2d4+2"
    }
  },
  "smoke_bomb": {
    "id": "smoke_bomb",
    "name": "Smoke Bomb",
    "type": "tool"
  },
  "guard_cloak": {
    "id": "guard_cloak",
    "name": "Silk Mask Cloak",
    "type": "tool"
  }
}
