// Auto-generated by build-data. Do not edit manually.
import type { ItemTemplate } from '../types/items'

export const ITEM_DICTIONARY: Record<string, ItemTemplate> = {
  "receipt": {
    "id": "receipt",
    "name": "Crumpled Receipt",
    "type": "tool"
  },
  "drow_baby": {
    "id": "drow_baby",
    "name": "Drow Baby",
    "type": "tool"
  },
  "macguffin_collar": {
    "id": "macguffin_collar",
    "name": "Leather Collar",
    "type": "tool"
  }
}
