// Auto-generated by build-data. Do not edit manually.
import type { StoryNode } from '../types/story'

export const STORY_NODES: Record<string, StoryNode> = {
  "n_start": {
    "id": "n_start",
    "type": "narrative",
    "text": "You awaken to rude morning light. Your head is pounding. The room is destroyed—furniture smashed, curtains torn. A white chicken pecks aimlessly at a spilled potion on the rug. You have no memory of last night.",
    "onEnter": [
      {
        "action": "adjust_hp",
        "amount": 20
      },
      {
        "action": "adjust_currency",
        "amount": 50
      }
    ],
    "choices": [
      {
        "id": "c_check_pockets",
        "label": "[Check your pockets]",
        "mechanic": {
          "type": "navigate",
          "nextNodeId": "n_inventory_check"
        }
      },
      {
        "id": "c_bathroom",
        "label": "[Check the Bathroom]",
        "mechanic": {
          "type": "navigate",
          "nextNodeId": "n_bathroom_door"
        }
      }
    ]
  },
  "n_inventory_check": {
    "id": "n_inventory_check",
    "type": "narrative",
    "text": "You rummage through your ruined clothes. You find a crumpled piece of paper.",
    "onEnter": [
      {
        "action": "add_item",
        "itemId": "receipt",
        "qty": 1
      },
      {
        "action": "set_flag",
        "key": "has_clue",
        "value": true
      }
    ],
    "choices": [
      {
        "id": "c_read_receipt",
        "label": "[Read the paper]",
        "mechanic": {
          "type": "navigate",
          "nextNodeId": "n_read_receipt"
        }
      }
    ]
  },
  "n_read_receipt": {
    "id": "n_read_receipt",
    "type": "narrative",
    "text": "It's a receipt from 'Dude Fiero's Kitchen'. Scrawled on the back is the word: 'OBLIVION'.",
    "choices": [
      {
        "id": "c_back_start",
        "label": "[Look around the room]",
        "mechanic": {
          "type": "navigate",
          "nextNodeId": "n_room_hub"
        }
      }
    ]
  },
  "n_room_hub": {
    "id": "n_room_hub",
    "type": "narrative",
    "text": "The hotel room is a disaster scene.",
    "choices": [
      {
        "id": "c_bathroom",
        "label": "[Open Bathroom Door]",
        "mechanic": {
          "type": "navigate",
          "nextNodeId": "n_bathroom_door"
        }
      },
      {
        "id": "c_closet",
        "label": "[Check the Closet]",
        "mechanic": {
          "type": "navigate",
          "nextNodeId": "n_closet"
        }
      },
      {
        "id": "c_leave",
        "label": "[Leave Hotel]",
        "mechanic": {
          "type": "navigate",
          "nextNodeId": "n_streets"
        }
      }
    ]
  },
  "n_closet": {
    "id": "n_closet",
    "type": "narrative",
    "text": "You open the closet. A Drow baby wearing a spider-themed pacifier stares up at you. It gurgles.",
    "onEnter": [
      {
        "action": "add_item",
        "itemId": "drow_baby",
        "qty": 1
      }
    ],
    "choices": [
      {
        "id": "c_take_baby",
        "label": "[Take the baby (carefully)]",
        "mechanic": {
          "type": "navigate",
          "nextNodeId": "n_room_hub"
        }
      }
    ]
  },
  "n_bathroom_door": {
    "id": "n_bathroom_door",
    "type": "encounter",
    "text": "You open the bathroom door. A massive Owlbear is drinking from the bathtub! It turns to you and roars.",
    "choices": [
      {
        "id": "c_fight",
        "label": "[Attack!]",
        "mechanic": {
          "type": "combat_init",
          "encounterId": "enc_bathroom"
        }
      },
      {
        "id": "c_calm",
        "label": "[Calm Down (Animal Handling DC 14)]",
        "mechanic": {
          "type": "skill_check",
          "dice": "1d20",
          "dc": 14,
          "onSuccess": {
            "nextNodeId": "n_calm_success"
          },
          "onFailure": {
            "nextNodeId": "n_calm_fail"
          },
          "onFailureEncounterId": "enc_bathroom",
          "attribute": "intelligence"
        }
      }
    ]
  },
  "n_calm_success": {
    "id": "n_calm_success",
    "type": "narrative",
    "text": "The beast sniffs your hand and purrs like a giant, feathered kitten. You notice a collar on it labeled 'MacGuffin'.",
    "onEnter": [
      {
        "action": "add_item",
        "itemId": "macguffin_collar",
        "qty": 1
      }
    ],
    "choices": [
      {
        "id": "c_leave_bath",
        "label": "[Back to Room]",
        "mechanic": {
          "type": "navigate",
          "nextNodeId": "n_room_hub"
        }
      }
    ]
  },
  "n_calm_fail": {
    "id": "n_calm_fail",
    "type": "narrative",
    "text": "The Owlbear does not appreciate your shushing. It swipes at you!",
    "choices": [
      {
        "id": "c_defend",
        "label": "[Defend Yourself]",
        "mechanic": {
          "type": "combat_init",
          "encounterId": "enc_bathroom"
        }
      }
    ]
  },
  "n_bathroom_victory": {
    "id": "n_bathroom_victory",
    "type": "narrative",
    "text": "The beast lies defeated. You find a leather collar on it labeled 'MacGuffin'.",
    "onEnter": [
      {
        "action": "add_item",
        "itemId": "macguffin_collar",
        "qty": 1
      }
    ],
    "choices": [
      {
        "id": "c_back",
        "label": "[Back to Room]",
        "mechanic": {
          "type": "navigate",
          "nextNodeId": "n_room_hub"
        }
      }
    ]
  },
  "n_streets": {
    "id": "n_streets",
    "type": "narrative",
    "text": "The bright sun of Sigil hurts your eyes. You recall you were heading to 'Drowtown' for the party.",
    "choices": [
      {
        "id": "c_go_drowtown",
        "label": "[Go to Drowtown Gate]",
        "mechanic": {
          "type": "navigate",
          "nextNodeId": "n_drowtown_gate"
        }
      }
    ]
  },
  "n_drowtown_gate": {
    "id": "n_drowtown_gate",
    "type": "narrative",
    "text": "A massive bouncer blocks the gate. 'Private party. Password?'",
    "choices": [
      {
        "id": "c_password",
        "label": "[Say 'OBLIVION']",
        "mechanic": {
          "type": "navigate",
          "nextNodeId": "n_mansion"
        },
        "visibilityRequirements": [
          {
            "type": "has_item",
            "itemId": "receipt"
          }
        ]
      },
      {
        "id": "c_show_baby",
        "label": "[Show the Drow Baby]",
        "mechanic": {
          "type": "navigate",
          "nextNodeId": "n_mansion_baby"
        },
        "visibilityRequirements": [
          {
            "type": "has_item",
            "itemId": "drow_baby"
          }
        ]
      },
      {
        "id": "c_no_clue",
        "label": "[Leave]",
        "mechanic": {
          "type": "navigate",
          "nextNodeId": "n_streets"
        }
      }
    ]
  },
  "n_mansion": {
    "id": "n_mansion",
    "type": "encounter",
    "text": "You enter Mik Tystone's mansion. He stands by a fountain. 'You stole my tiger! And my chicken!'",
    "choices": [
      {
        "id": "c_fight_mik",
        "label": "[Fight Mik Tystone]",
        "mechanic": {
          "type": "combat_init",
          "encounterId": "enc_boss"
        }
      }
    ]
  },
  "n_mansion_baby": {
    "id": "n_mansion_baby",
    "type": "narrative",
    "text": "The bouncer's eyes go wide. 'That's Mik's kid! Get in here!' You are ushered into the VIP lounge.",
    "choices": [
      {
        "id": "c_win",
        "label": "[Finish the Adventure]",
        "mechanic": {
          "type": "navigate",
          "nextNodeId": "n_victory"
        }
      }
    ]
  },
  "n_victory": {
    "id": "n_victory",
    "type": "ending",
    "text": "You return the baby/chicken/tiger. Tystone laughs and offers you a drink. 'Hair of the dog?' The nightmare starts all over again."
  },
  "n_game_over": {
    "id": "n_game_over",
    "type": "ending",
    "text": "The Hangover claims another victim.",
    "choices": [
      {
        "id": "c_restart",
        "label": "[Restart]",
        "mechanic": {
          "type": "navigate",
          "nextNodeId": "n_start"
        }
      }
    ]
  }
}
